spring:
  datasource:
    url: "INVALID!"
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 20
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
  sql.init.mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/static/
logging:
  level:
    org:
      hibernate.type.descriptor.sql: trace
      springframework:
        security: DEBUG
        web.cors: DEBUG
